# Non Graded Challenge 4 - Linear Algebra - Matrix

---

## Assignment Instructions

- Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$



---
## Answer

### Problem 1

Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

In [1]:
# Define the Tensor

import numpy as np

vect_1 = np.array([ 
                   [[23, 50], [7, 12]], 
                   [[57, 67], [99, 43]],
                   [[75, 21], [57, 12]],
                   [[87, 26], [18, 84]],
                   ])
vect_1

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

---
### Problem 2

Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$


In [2]:
# Define the Matrix A & B

A = np.array([
              [23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]
              ])

B = np.array([17, 22, 19])

print('Vector A : \n', A)
print('')
print('Vector B : \n', B)

Vector A : 
 [[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

Vector B : 
 [17 22 19]


In [3]:
# Matrix Multiplication

A @ B

array([1852, 2454, 4305])

---
### Problem 3

Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

In [4]:
# Define the Matrix

vect_3 = np.array([ 
                   [23, 50, 19],
                   [7, 12, 109],
                   [57, 67, 98]
                   ])

In [5]:
# Transpose

vect_3.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [6]:
# Determinant

np.linalg.det(vect_3)

131344.0000000002

In [7]:
# Inverse

np.linalg.inv(vect_3)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])