In [1]:
import numpy as np

In [2]:
A = np.array([[3, 1],
            [0, 2]])
A

array([[3, 1],
       [0, 2]])

In [3]:
x1 = np.array([-1, 0])
x2 = np.array([-1, 1])

In [4]:
val, vec = np.linalg.eig(A)
val

array([3., 2.])

In [5]:
vec

array([[ 1.        , -0.70710678],
       [ 0.        ,  0.70710678]])

In [6]:
np.linalg.norm([5, 12])

13.0

In [7]:
B = np.array([[-5, 2],
[-7, 4]])
B

array([[-5,  2],
       [-7,  4]])

In [8]:
valB, vecB = np.linalg.eig(B)
valB

array([-3.,  2.])

In [9]:
vecB

array([[-0.70710678, -0.27472113],
       [-0.70710678, -0.96152395]])

In [10]:
np.linalg.norm(vecB[:,0])

0.9999999999999999

In [11]:
vecB[:,0]

array([-0.70710678, -0.70710678])

In [12]:
a = np.array([[3, 1], [0, 2]])
val, vec = np.linalg.eig(a)

In [13]:
val

array([3., 2.])

In [14]:
vec

array([[ 1.        , -0.70710678],
       [ 0.        ,  0.70710678]])

In [15]:
np.diag(val)

array([[3., 0.],
       [0., 2.]])

In [17]:
np.linalg.inv(vec)

array([[1.        , 1.        ],
       [0.        , 1.41421356]])

In [18]:
vec@np.diag(val)@np.linalg.inv(vec)

array([[3., 1.],
       [0., 2.]])