In [1]:
import numpy as np


In [2]:
tinggi = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
berat = [60.5, 61.5, 62.5, 63.5, 64.5, 65.6]

berat/tinggi

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
np_tinggi= np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

array([35.58823529, 34.16666667, 32.89473684, 57.72727273, 58.10810811,
       58.57142857])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
print(np.arange(3,9,2))

[3 5 7]


In [7]:
arr= np.array([1,2,3,4])
arr_new= np.append(arr, [7,8,9])

In [8]:
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [9]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

# 0-D/skalar

In [10]:
arr= np.array(6)
print(arr)

6


In [11]:
arr.ndim #jumlah dimensi

0

In [12]:
arr.shape

()

# 1-D/vektor

In [13]:
arr= np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [14]:
arr.ndim

1

In [15]:
arr.shape

(4,)

# 2-D/matriks

In [23]:
arr= np.array([[1, 2, 3, 4], 
            [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
arr.size

8

In [17]:
arr.ndim

2

In [18]:
arr.shape

(2, 4)

# latihan

In [19]:
arr= np.array([[[1, 2, 3, 4]]])
print(arr)

[[[1 2 3 4]]]


In [20]:
arr.ndim

3

In [21]:
arr.shape

(1, 1, 4)

In [22]:
arr.size

4

In [30]:
arr= np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [32]:
matriks= arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [33]:
matriks2= arr.reshape(6,1)
print(matriks2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [38]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [35]:
a.shape

(6,)

In [39]:
a2= a[np.newaxis]
# a2= a[np.newaxis, :]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
a3=a[:, np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [42]:
a_e= np.expand_dims(a, axis=1)
a_e.shape

(6, 1)

In [44]:
a_e

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
a_e2= np.expand_dims(a, axis=0)
a_e2.shape[0]

1

In [45]:
a_e2

array([[1, 2, 3, 4, 5, 6]])

In [47]:
arr_2d= np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [49]:
arr_2d.shape

(2, 4)

In [50]:
a_e2= np.expand_dims(arr_2d, axis=1)
a_e2.shape

(2, 1, 4)

# soal

In [51]:
arr= np.array([1,2,7,4,10,5])
print(arr[2:6])

[ 7  4 10  5]


In [52]:
arr= np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [53]:
arr= np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [54]:
arr= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[0,2])

3


In [57]:
print(arr[1,2:4])

[7 8]


In [56]:
print(arr[2,2:4])

[11 12]


In [63]:
arr= np.array([[1, 2, 3, 4,8,10], [5, 6, 7, 8,7,10], [9, 10, 11, 12,11,12]])
print(arr[:4:2,2])
print(arr[1:2,2:3])

[ 3 11]
[[7]]


In [65]:
arr_cek= arr[arr>=3]
arr_cek.ndim

1

In [66]:
a_1 = np.array([[1,1],
                [2,2]])

a_2 = np.array([[3,3],
                [4,4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [70]:
arr_new= np.array([1, 2, 3, 4,5, 6,7,8,9,10, 11, 12])
new_arr = arr_new.reshape(2,3,-1) 
print(new_arr.shape)
print(new_arr)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
ravel
flatten