In [1]:
import numpy as np

In [5]:
A = np.array([[3, 1],
            [0, 2]])
A

array([[3, 1],
       [0, 2]])

In [14]:
x1 = np.array([-1, 0])
x2 = np.array([-1, 1])

In [6]:
val, vec = np.linalg.eig(A)
val

array([3., 2.])

In [7]:
vec

array([[ 1.        , -0.70710678],
       [ 0.        ,  0.70710678]])

In [39]:
np.linalg.norm([5, 12])

13.0

In [41]:
B = np.array([[-5, 2],
[-7, 4]])
B

array([[-5,  2],
       [-7,  4]])

In [43]:
valB, vecB = np.linalg.eig(B)
valB

array([-3.,  2.])

In [44]:
vecB

array([[-0.70710678, -0.27472113],
       [-0.70710678, -0.96152395]])

In [45]:
np.linalg.norm(vecB[:,0])

0.9999999999999999

In [50]:
vecB[:,0]

array([-0.70710678, -0.70710678])